apiVersion: v1
kind: Service
metadata:
  name: legalllm-service
  namespace: legalllm
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
spec:
  type: LoadBalancer
  selector:
    app: legalllm
    tier: frontend
  ports:
    - port: 80
      targetPort: 8501
      protocol: TCP
      name: http
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours